# Generated by Django 3.0.7 on 2020-06-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200211_1555'),
    ]

    operations = [
        migrations.RenameModel("Question", "Class1")
    ]
